name: 'Hello World'
description: 'Greet someone and record the time'
branding:
  icon: 'circle'
  color: 'blue'
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
  CLARIFAI_PAT:
    required: true
  CLARIFAI_USER_ID:
    required: true
  CLARIFAI_APP_ID:
    required: true

outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.sha }}
        fetch-depth: 2
    - uses: actions/setup-node@v3
      with:
        node-version: 16
      shell: bash
    - run: 'dist/index.js'
      env:
        ACTION_REF: ${{ github.action_ref || env.BRANCH }}
        GIT_COMMIT_HASH: ${{ github.event.pull_request.head.sha }}
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
        LINK: "https://github.com/${{ github.repository }}/pull/${{ github.event.pull_request.number }}"
        PR_TITLE: ${{ github.event.pull_request.title }}
        BRANCH:  ${{ env.BRANCH }}
        PATCH_PR: ${{ github.event.pull_request.number }}
        PATCH_REPO: ${{ github.repository }}
        CLARIFAI_PAT: ${{ inputs.CLARIFAI_PAT }}
        CLARIFAI_USER_ID: ${{ inputs.CLARIFAI_USER_ID }}
        CLARIFAI_APP_ID: ${{ inputs.CLARIFAI_APP_ID }}
        CLARIFAI_MODEL_ID: ${{ inputs.CLARIFAI_MODEL_ID | 'llama2-70b-chat' }}
        MODEL_VERSION_ID: ${{ inputs.MODEL_VERSION_ID | '6c27e86364ba461d98de95cddc559cb3' }}