name: 'clarifai-PR'
description: 'PR review with clarifai'
branding:
  icon: 'circle'
  color: 'blue'
inputs:
  GITHUB_TOKEN:
    required: true
  CLARIFAI_PAT:
    required: true
  CLARIFAI_USER_ID:
    required: true
  CLARIFAI_APP_ID:
    required: true
  CLARIFAI_MODEL_ID:
    required: true

runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.sha }}
        fetch-depth: 2
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: build
      run: 'npm install'
      shell: bash
    - name: install ncc
      run: 'npm i -g @vercel/ncc'
      shell: bash
    - name: build
      run: 'npm run build'
      shell: bash
    - name: diff
      shell: bash
      run: 'git --no-pager diff HEAD^ HEAD --output=diff-file'
    - name: check
      shell: bash
      run: 'node dist/index.js'
      env:
        ACTION_REF: ${{ github.action_ref || env.BRANCH }}
        GIT_COMMIT_HASH: ${{ github.event.pull_request.head.sha }}
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
        LINK: "https://github.com/${{ github.repository }}/pull/${{ github.event.pull_request.number }}"
        BRANCH:  ${{ env.BRANCH }}
        PR_TITLE: ${{ github.event.pull_request.title }}
        PR_NUMBER: ${{ github.event.number }}
        PR_REPO: ${{ github.repository }}
        PR_OWNER: ${{ github.repository_owner }}
        CLARIFAI_PAT: ${{ inputs.CLARIFAI_PAT }}
        CLARIFAI_USER_ID: ${{ inputs.CLARIFAI_USER_ID }}
        CLARIFAI_APP_ID: ${{ inputs.CLARIFAI_APP_ID }}
        CLARIFAI_MODEL_ID: ${{ inputs.CLARIFAI_MODEL_ID }}
