on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: clarifai-pr
    steps:
      - name: Review pull request code with clarifai.com
        id: hello
        uses: tot-ra/clarifai-PR@main
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CLARIFAI_PAT: ${{ secrets.CLARIFAI_PAT }}
          CLARIFAI_USER_ID: ${{ secrets.CLARIFAI_USER_ID }}
          CLARIFAI_APP_ID: ${{ secrets.CLARIFAI_APP_ID }}
          CLARIFAI_MODEL_ID: 'llama2-70b-chat'